version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "npm"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 5
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/coverage-v8"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/coverage-v8"
